services:
  backend:
    build: .
    container_name: homeflix-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    ports:
      - "5500:5500"
    volumes:
      - ./logs:/app/logs

  db:
    image: postgres:16-alpine
    container_name: homeflix-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: homeflix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pasword123test
    ports:
      - "5050:80"
  redis:
    image: redis:7-alpine
    container_name: homeflix-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data: