services:
  db:
    image: postgres:16-alpine
    container_name: homeflix-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: homeflix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres && echo 'Database is ready'" ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: homeflix-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  db-init:
    image: node:20-alpine
    working_dir: /app
    profiles: [ "init" ]
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/homeflix
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy
    entrypoint: [
      "sh",
      "-c",
      "echo 'Initialisiere Datenbank...' && npx prisma migrate reset --force --schema=./prisma/schema.prisma && echo 'Datenbank wurde erfolgreich initialisiert!'"
    ]
    restart: "no"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgresql://postgres:postgres@db:5432/homeflix
        REDIS_URL: redis://redis:6379
    container_name: homeflix-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/homeflix
      REDIS_URL: redis://redis:6379
      NODE_ENV: development
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    ports:
      - "5500:5500"
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5500/ && echo 'Backend ist bereit'" ]
      interval: 30s
      timeout: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: homeflix-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pasword123test
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
  redis_data: