blank_issues_enabled: false
contact_links:
  - name: Report a security issue (private)
    url: https://github.com/mariokreitz/Homeflix/security/advisories/new
    about: Use this link to report vulnerabilities confidentially.